---
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEYzCCA0ugAwIBAgIRAJPOvRLkPcLaNsd9Zwdl9oAwDQYJKoZIhvcNAQELBQAw
    gb0xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEbMBkGA1UEBxMSU2lsaWNvbiBW
    YWxsZXkgTGFiMRQwEgYDVQQKEwtEYXRhIGFuZCBBSTEaMBgGA1UECxMRSUJNIERh
    dGEgUGxhdGZvcm0xGzAZBgNVBAMTEklCTS1EYXRhLWFuZC1BSS1DQTE1MDMGCSqG
    SIb3DQEJAQwmaWJtLWFuYWx5dGljcy1kYXRhLXBsYXRmb3JtQHVzLmlibS5jb20w
    IBcNMjUxMDE5MTk0ODQ0WhgPMjEyNTEwMTkxOTQ4NDRaMIG9MQswCQYDVQQGEwJV
    UzELMAkGA1UECBMCQ0ExGzAZBgNVBAcTElNpbGljb24gVmFsbGV5IExhYjEUMBIG
    A1UEChMLRGF0YSBhbmQgQUkxGjAYBgNVBAsTEUlCTSBEYXRhIFBsYXRmb3JtMRsw
    GQYDVQQDExJJQk0tRGF0YS1hbmQtQUktQ0ExNTAzBgkqhkiG9w0BCQEMJmlibS1h
    bmFseXRpY3MtZGF0YS1wbGF0Zm9ybUB1cy5pYm0uY29tMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAz7EO+dvZp+1XLeE9zxinMX8lyFoAwK0exdClmlEF
    l0ls2nv9hGbFBDZftLKCUseXpLLawz8YDmLDfdl/TtKCab5RUHi1883YlOkvA4mU
    7jTMJR4TUYv74RFJSAT4sYAjq8IG8nj6Oc8dUeodFZl4vjK6ivNeo8GBCFBPSwhJ
    +BiffXzUQgZw3abn2IrwTx2q17OuU59hskTd/pkvCCniUu6n7ddy13AtTPF/vCv5
    cAaPcej9ByieY+eqrIf3B4h2Y+DG/6jhakOipzJmhL4X7DZz5AjlHyN3rVdHncOS
    xTnHnKbwTsWkFYZzjhabJiRgzzdffgA7WwNrWt4EL9aH7wIDAQABo1owWDAOBgNV
    HQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYBBQUHAwEwEgYDVR0TAQH/BAgwBgEB
    /wIBATAdBgNVHQ4EFgQUM6v2mTI3zpa8/KcVcy/7WZrIZhcwDQYJKoZIhvcNAQEL
    BQADggEBACrvUjzHiVhZdjoRyl4YPRadNb4pDZgAsmWEo2Hzr7XynR7awVs29mx4
    0CYbLNCHD0O6Ns8zwBkTaRmUIFLEQSq19IyZHNnDtEa2gQD0OAECjZrnud/3WTk9
    aHgFeEgsfWq0KXhO1pHgCWGNiko0wpIap7QCrHcKmcMD5IUK848CEo9zTyanxYqr
    1DbKjjANkSfNST/JGOEUfKF6/zJmcyhhh1wZxjOTV+zlxac6TPBLMzqL+VXwD4wJ
    bJ+QWu0EvgPdTdGBF3XF+5TGu8UtVCkXa0FzMgkh+xrr2WPSaoDImJm+MMYlrCl7
    butPhL+vIckTzDB+dpIrGTsAYZdN1E0=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: ocp4732-nginx-ca
---
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBDCCAeygAwIBAgIQMFBPWb6+fhYDP8QijFhLBjANBgkqhkiG9w0BAQsFADAc
    MRowGAYDVQQDExFjcy1jYS1jZXJ0aWZpY2F0ZTAeFw0yNTExMjEyMTQ4NDJaFw0y
    NzExMjEyMTQ4NDJaMBwxGjAYBgNVBAMTEWNzLWNhLWNlcnRpZmljYXRlMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7rngVegwFZbs9Z3/Yknpxtvbfq5k
    GnWI0/JmBmqvEH4tagZ2e7NLjCKhup74HzW0nkGyLYGOSoVtOxRdh1eR7z3jEER+
    pngoVVlW56PFnPYusU6u9X5gGHMbbUoz5uZcwn0kuKiCyH9huhgZSPZjr+ummYgG
    wDTFGRwRf3yeVel3N8+kopUWxpmKMs3m+4T9YTN0ei8YxJj7hrjUlfIU6wYavST8
    9CnDyx/OAWvljB3veQfIwIHlJjFWpmV4tH6okbsIS7VCPUvLu3cNfen0m04Fqeqm
    Sp/VxHjqXgGkxbtl8f/E6wyXbX1UhOBtA2vCEz2qSVbBKt6sftTSt4kaKQIDAQAB
    o0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
    9n9PPSjNs8605XQVqXHwcolcln4wDQYJKoZIhvcNAQELBQADggEBAFYA6T0xJfHZ
    e5qeMzgphtLgczVWnWO/6QlD+ITAfeSbO8BEQwxe/VUwNnniZF4+86sfNH7v4b2y
    4+PiTKL1+MSnm86vC1TD1UMVLWmN+VdGUy5qUHMd80F95m8fedCW/L2xr+qOB8w7
    z4hMfPrfTbGI2EKIFA3RRDV2sPU1q7G6JchHjyacIYdx/71vMf0PUxLsBRfo7xbP
    6JEMJN8DlFyZ+vSWhbRTIHZQ5nZFSJ19sHya0ZIsScRLmLvA5y00y4yro2PKQZ7o
    LVVdv5KihzmKs4PDN6atTtieWx5NByFT56fAgz2uu4dDlv2KsR/6kXgDcrQfuJpN
    cuDXX/D/IEc=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: ocp4732-iam-ca
