---
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEYjCCA0qgAwIBAgIQCnjtVPg0OmdaBE8mpf5QwzANBgkqhkiG9w0BAQsFADCB
    vTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRswGQYDVQQHExJTaWxpY29uIFZh
    bGxleSBMYWIxFDASBgNVBAoTC0RhdGEgYW5kIEFJMRowGAYDVQQLExFJQk0gRGF0
    YSBQbGF0Zm9ybTEbMBkGA1UEAxMSSUJNLURhdGEtYW5kLUFJLUNBMTUwMwYJKoZI
    hvcNAQkBDCZpYm0tYW5hbHl0aWNzLWRhdGEtcGxhdGZvcm1AdXMuaWJtLmNvbTAg
    Fw0yNTEyMTkxNTMyNDFaGA8yMTI1MTIxOTE1MzI0MVowgb0xCzAJBgNVBAYTAlVT
    MQswCQYDVQQIEwJDQTEbMBkGA1UEBxMSU2lsaWNvbiBWYWxsZXkgTGFiMRQwEgYD
    VQQKEwtEYXRhIGFuZCBBSTEaMBgGA1UECxMRSUJNIERhdGEgUGxhdGZvcm0xGzAZ
    BgNVBAMTEklCTS1EYXRhLWFuZC1BSS1DQTE1MDMGCSqGSIb3DQEJAQwmaWJtLWFu
    YWx5dGljcy1kYXRhLXBsYXRmb3JtQHVzLmlibS5jb20wggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDV/PTvh+50d0ZF//yaStPkFz1idsps7NJnSJH46cd5
    KxGX9sv8Cm7SxgRXLduB8nLIkVFxonqo23hA3JkY36jLtx1EVogXd1cQ7VN3MgcR
    4xEdj3GarN713JcVbQTJznYpV43d8rKXkam5K/YB+hoya2POUHKtgcbLDXrxAiD2
    RVxRfQdTZwtLxVRO8Zl3D6akchjiYxqnh4l2fIkO8spsJNlPFmnhppoK1L9mpG+M
    Dsq33TiN6nfhVJB9KVAXu2uRLmwo1JUgMosZRdexvq3kKwn7VpAwMA1mBiebM69C
    60iH3kBGzs0OCqdtJVbKyspTnN6AsV9fM7C68P0CLFQxAgMBAAGjWjBYMA4GA1Ud
    DwEB/wQEAwIBBjATBgNVHSUEDDAKBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
    AgEBMB0GA1UdDgQWBBQ8UfBwl8qEwGgYqkJFkzgk+DC5JTANBgkqhkiG9w0BAQsF
    AAOCAQEAInpu1XvFKct0pY6h+xNcWobk4ShgMTIos/I0hpE8u9mp1ePxS9fpBOR5
    57QRxYpdAaxnOm90gzn2+sexppWgxIPr8dGIFn4rgRlfET6Xcfd15rTfGbnsUVWJ
    q9MyYoUJlI0J+bKIpxkdkzIdVwO0UWFyV03rm1hhUvy1CMAiXKVHbXAVwLsjjlDA
    5ESNh5+dI8t2o99QFGekHafl5f7FvHJp/mWbV1TAE0cYFTNb55DYnkSUnjNAEfW8
    lRu2l+1O/+oX2mJZ6nSyhel50ezKS807hd8+hKLU6doJNB9JjzquiPoJnN37PWzi
    fg4xxMakl0MzqW4oQQWmXShaqpVOvg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: ocp4732-nginx-ca
---
apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIRAO4UhmSQM/TH9Lm/qxx9Hm4wDQYJKoZIhvcNAQELBQAw
    HDEaMBgGA1UEAxMRY3MtY2EtY2VydGlmaWNhdGUwHhcNMjUxMjE5MTYyOTUxWhcN
    MjcxMjE5MTYyOTUxWjAcMRowGAYDVQQDExFjcy1jYS1jZXJ0aWZpY2F0ZTCCASIw
    DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPzUjtIPRDy4iIP2BmpOGY9CyuAr
    5ak1+PIh5WWYr6kbGYj1OBzukxJ/+x8cy9/AR8rgvnoWPsKzJiSMfQXKUSCuz6nK
    EvldjAz+0qSquvG0Z2GclfjUTzUQ/fHLqxAISswyNrrry7K3PKo1IiZLOcZFaUre
    GidC/2ghHcOrDFaJX8BF0Hm/J2cqZHZv7Kee4IComxX5ETAKRjNbUUK3aQWbiKWf
    ZP9RFQwUgILvpop5mc7TaUVsi+U3Qvzjjegj0wwW02a9kVu3aIZcaO4ckbEQWp2F
    +Q2GcKlcBZkO4/gXlBOsZMdX+6a3iVVB4ttBzpLjS3OHQ9YrN0NldJdahE8CAwEA
    AaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE
    FB7Rb3XTNartC+By+iA4Ty9EQFGBMA0GCSqGSIb3DQEBCwUAA4IBAQBIBgF/gFnI
    qN35txf4NzV65BDVY/+MmM46GETlkHUkU8C5fs1HRbzph2RlrfJM9/IKmXzPHar9
    FkaSAox0CEZ9YBurKFCo5s9nHmXqi4HRN9C1K7XhuRmOhzBSOaKFlawyOhR3VtiF
    3RWSeof213Ck4Woa1L8FbfYaiwGMTnqUMHhwzE0cwUM2cmr2YnG0P1N1ZlTygK6U
    ZBjxHqemDFdO83rW9gvZg0FxkTrvJ66IH0toTqj/I0gmkq9aRY/eOSgOvvOojhTg
    daYDRJ5PFXTK02qm0KJy+nrzFbvUZQ5MRsbPOn+hui2V5HQGaVlhtFvqGIlyQzeQ
    MDNs/emk+gra
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: ocp4732-iam-ca
