# values.yaml
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.apps.ocp4732.cp.fyre.ibm.com`)
    entryPoints:
      - web
providers:
  kubernetesGateway:
    enabled: true
gateway:
  name: "zen-gateway"
  listeners:
    web:
      namespacePolicy:
        from: All
    websecure:
      # -- Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
      # The port must match a port declared in ports section.
      port: 8443
      # -- Optional hostname. See [Hostname](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Hostname)
      #hostname:
      # Specify expected protocol on this listener See [ProtocolType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ProtocolType)
      protocol: HTTPS
      # -- Routes are restricted to namespace of the gateway [by default](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.FromNamespaces)
      namespacePolicy:
        from: All
      # -- Add certificates for TLS or HTTPS protocols. See [GatewayTLSConfig](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayTLSConfig)
      certificateRefs:
      - kind: Secret
        name: ocp4732      
      # -- TLS behavior for the TLS session initiated by the client. See [TLSModeType](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.TLSModeType).
      mode: Terminate
service:
  type: NodePort
#logs:
#  general:
#    level: DEBUG

